to make update
gsg-K1-FC/storag-obaid pull request #1
Opened 2020-10-29 20:01 UTC by obaidofj

first upload , then i will change the code to add update and sort

2020-10-30 23:12 UTC, saharAdem commented on script.js
> +        }
you can create a parent div for these two divs and then hide the parent div instead of using for loop.

2020-10-30 23:13 UTC, saharAdem commented
GREAT JOB, However, try to write more convenient names for your variables

2020-10-30 23:13 UTC, saharAdem approved these changes

2020-10-31 16:35 UTC, Rahaf-96 requested changes

2020-10-31 16:35 UTC, Rahaf-96 commented on script.js
> +  //console.log(description, "des");
remove unnecessary comments, please

2020-10-31 16:35 UTC, Rahaf-96 commented on script.js
> +    console.log(notes, "notes");
remove `console.log`

2020-10-31 16:35 UTC, Rahaf-96 commented on script.js
> +document.getElementById("add-btn").addEventListener("click", function () {
if the user press `space` as an input, it will add an empty list item. you should handle this case too.

2020-10-31 16:35 UTC, Rahaf-96 commented on script.js
> +        //console.log(i);
remove this comment too.

2020-10-31 16:35 UTC, Rahaf-96 commented on style.css
> +  /* transform: translate(-50%,-50%); */
remove this comment.

2020-10-31 17:04 UTC, Rahaf-96 approved these changes
Great job!!

2020-10-31 17:07 UTC, merged